### ISSUE TITLE
Some questions

### ISSUE THREAD

**Issue by dancancro** [gothinkster/kotlin-spring-realworld-example-app#2]
Hi, I am working on adding this project as a part of [my amalgam of various demos](https://github.com/dancancro/great-big-example-application/tree/blogwithkotlin/src/main/kotlin/org/exampleapps/greatbig) and I have a couple questions.

1) Why did you choose not to use Spring Security?

2) How does the tagList of an Article work? 
I'm getting the following error from [this code in my app](https://github.com/dancancro/great-big-example-application/blob/blogwithkotlin/src/main/kotlin/org/exampleapps/greatbig/domain/Article.kt#L29) and I'm wondering why I don't get it in the original 

> Caused by: org.h2.jdbc.JdbcSQLException: Table "ARTICLE_TAG_LIST" not found; SQL statement:
select taglist0_.article_id as article_1_2_0_, taglist0_.tag_list_id as tag_list2_2_0_, tag1_.id as id1_20_1_, tag1_.name as name2_20_1_ from article_tag_list taglist0_ inner join tag tag1_ on taglist0_.tag_list_id=tag1_.id where taglist0_.article_id=? [42102-195]

**Comment by ghost** [comment]
I've been searching for a Spring Boot + Spring Security + Kotlin solution but haven't found anything yet. I would also like to know why aren't you using Spring Security.

**Comment by MatthiasKauer** [comment]
In the [original issue](https://github.com/gothinkster/realworld/issues/93), the author said

> Regarding Spring Security, I think its too complex to implement for such a simple use case (extracting the Authorization header, check in db then parse the JWT).

**Comment by geromegrignon** [comment]
Closing as answered
