### ISSUE TITLE
Serving Static Resources

### ISSUE THREAD

**Issue by napperley** [gothinkster/kotlin-spring-realworld-example-app#3]
Does the back-end have a designated place for serving up static resources (eg JS, CSS, and HTML files)?

**Comment by rgoomar** [comment]
@napperley It's usually from the `src/main/resources` directory
See docs for more details, but it can be configured to be elsewhere. https://docs.spring.io/spring-boot/docs/current-SNAPSHOT/reference/htmlsingle/#boot-features-spring-mvc-static-content
Note - these are spring boot 2.x docs

**Comment by napperley** [comment]
In that case it should be mentioned in the documentation where static resources reside since it isn't obvious.

**Comment by agrison** [comment]
It's classic Spring.

**Comment by geromegrignon** [comment]
Closed as answered.
